name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build
        shell: cmd
        run: |
          build.bat && tar -acf ic.zip ic.exe ic.dll
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          inputs:
            arch: x86
          name: ic
          path: |
            ic.zip
