name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: 'x86'
      - name: build
        shell: cmd
        run: |
          build.bat
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: ic
          path: |
            ic.exe
            ic.dll
